language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
  #- npm install hexo-helper-qrcode --save
  #- npm install hexo-generator-feed --save

script:
  - hexo g

after_script:
  - cd ./public
  - if [ $MY_DOMAIN ]; then echo ${MY_DOMAIN} > CNAME; fi
  - git init
  - git config user.name "anjia0532"
  - git config user.email "anjia0532@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/anjia0532/anjia0532.github.io.git
   - MY_DOMAIN: anjia.ml